# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master ]
    paths:
      - "**.py"
      - ".github/workflows/testing.yml"
  pull_request:
    branches: [ master ]
    paths:
      - "**.py"
      - ".github/workflows/testing.yml"
  schedule:
    - cron: "0 0 * * 0"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
        pytorch-version: ['2.0.1']
    env:
      PYTORCH_VERSION: ${{ matrix.pytorch-version }}
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: "pip"
        cache-dependency-path: "pyproject.toml"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel setuptools
        pip install -e ."[dev]"
        pip install torch==${{ matrix.pytorch-version }}
        
    - name: Run info
      run: |
        which python && python --version && python -c 'import torch; print("torch", torch.__version__)'
    - name: Run Linters
      run: make lint
    - name: Run Tests
      run: |
        pytest -v geoopt tests --durations=0 --doctest-modules --cov geoopt --cov-report=xml --cov-report term 
    - name: Coveralls
      uses: codecov/codecov-action@v4.3.0
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        env_vars: PYTORCH_VERSION
